server:
  port: 3001
  # The format used for the keystore. It could be set to JKS in case it is a JKS file
#  ssl:
#    key-store-type: PKCS12
#    # The path to the keystore containing the certificate
#    key-store: classpath:keystore.p12
#    # The password used to generate the certificate
#    key-store-password: N@mber_11
#    # The alias mapped to the certificate
#    key-alias: keystore
#    enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

spring:
  webflux:
    base-path: /api
  profiles:
    active: dev
  data:
    mongodb:
#      uri: mongodb://localhost:27017,localhost:27018/?replicaSet=rs0
      database: qwangu_db
      host: localhost
      port: 27017
      username: kevin
      password: pass123
      auto-index-creation: true
      authentication-database: admin
#      replica-set: myreplicaset
    
jwt:
  secret: "ahasjofnwowuwoeneoeneowbnkamalspsiwnwpsndifnfpoe"
  expiration: 3600

mail:
  host: 127.0.0.1
  port: 3025
  username: person@gmail.com
  password: testing

company:
  name: proaktivio
  url: https://proaktivio.co.ke
  no-reply-email: noreply@proaktivio.co.ke
  social-media:
    linked-in-url: https://linked-in.com/proaktivio
    twitter-url: https://twitter.com/proaktivio
    facebook-url: https://facebook.com/proaktivio
    instagram-url: https://instagram.com/proaktivio

api:
  end-points:
    - http://localhost:3001/
ui:
  end-points:
    - http://localhost/activate/?token=
    - http://localhost/forgot-password/?token= 
    - http://localhost/sign-in

ftl:
  templates:
    -
#   TODO - REMOVE BELOW LINKS AND USE FOR COMPANY
      models:
        - https://linked-in.com
        - https://twitter.com
        - https://facebook.com
        - https://instagram.com
        - Designed by PROAKTIVIO
      resources:
        - templates/images/company-logo.png
        - templates/images/password.jpg
        - templates/images/footer.png
        - templates/images/linkedin.png
        - templates/images/twitter.png
        - templates/images/facebook.png
        - templates/images/instagram.png
        - templates/images/invoice.jpg
        - templates/images/payment.jpg
        - templates/images/welcome.jpg
    -
      name: activate_account.ftlh
      path: src/main/resources/templates
    -
      name: set_password.ftlh
      path: src/main/resources/templates
      resources:
        - templates/images/resetPassword/password_reset.gif
    -
      name: invoice.ftlh
#       TODO - ADD TEMPLATE FOR PAYMENT CONFIRMATION
    -
      name: receipt.ftlh
    -
      name: welcome.ftlh
safaricom:
  whiteListedUrls:
    - '127.0.0.1'
    - proactivio-qwangu.ddns.net
    - localhost

rent:
  cronToCreateInvoice: '0 0/1 * * * ?'
  dueDatePerMonth: 5
  penaltyPercentageOfRent: 20

notice:
  levelOne: 1
  levelTwo: 0.75
  levelThree: 0.5
  levelFour: 0.25
  levelFive: 0
  
notifications:
  send-sms: 'true'
  sender-id: 'PROAKTIVIO'
  