server:
  port: 8080
#  servlet:
#    context-path: /api
spring:
  data:
    mongodb:
      database: qwangu_db
      host: localhost
      port: 27017
      username: kevin
      password: pass123
      auto-index-creation: true
      authentication-database: admin
jwt:
  secret: ahasjofnwowuwoeneoeneowbnkamalspsiwnwpsndifnfpoe
  expiration: 3600