server:
  port: 8080
#  servlet:
#    context-path: /api
spring:
  data:
    mongodb:
      database: qwangu_db
      host: localhost
      port: 27017
      username: kevin
      password: pass123
      auto-index-creation: true
      authentication-database: admin
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: ksksks
#    password: kskskks
#    properties:
#      mail:
#        transport:
#          protocol: smtp
#        smtp:
#          auth: true
#          starttls:
#            enable: true
jwt:
  secret: ahasjofnwowuwoeneoeneowbnkamalspsiwnwpsndifnfpoe
  expiration: 3600
email:
  mail:
    host: 127.0.0.1
    port: 587
    username: person@gmail.com
    password: testing
  noReply: noreply@proaktivio.co.ke
  template:
    activate-account: activate_account.ftl
  resource:
    activate-account-url: http://localhost:8080/user/activate
